# Generated by Django 6.0.2 on 2026-03-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_barbeiro', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(default='Nenhum', max_length=20)),
                ('cliente_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('barbeiro_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barbeiro')),
            ],
        ),
    ]
