# Generated by Django 6.0.2 on 2026-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atendimento_valor_alter_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'Pix')], default='dinheiro', max_length=100),
        ),
    ]
