# Generated by Django 6.0.2 on 2026-04-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_atendimento_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='tipo_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'Pix')], default='dinheiro', max_length=100, null=True),
        ),
    ]
